# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e994502dd58fd4837b0e4307c3c43e5d745d8c48504a10b855841c6ca4dccbcd2979e3f870f5631a987b1b0d395b7d3d0121629e6e07dac21763776e0ead302

test:
  secret_key_base: bbd9023da99f7c6b45b95e94fc74d87fd03d6cbdc042f28615f70f26e76f4ec6cfec8a0732055279e45fa36e7dcb9785b2aa9dafba7df81482f83742e1fb53a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
